### ISSUE TITLE
can support kotlin 1.1 coroutines?

### ISSUE THREAD

**Issue by arden** [vert-x3/vertx-lang-kotlin#10]
kotlin 1.1 has released, and support coroutines, vert.x can support kotlin's coroutines?

**Comment by alanyang** [comment]
+1

**Comment by JonasGao** [comment]
+1

**Comment by stream1984** [comment]
That would be great but i think feature of coroutine should be in another project such as vertx-sync-kotlin.

**Comment by fvasco** [comment]
Basic coroutine support #14

**Comment by stream1984** [comment]
Copy the vertx-sync [vertx-kotlin-coroutine](https://github.com/stream1984/vertx-kotlin-coroutine) with kotlin and coroutine.

**Comment by stream1984** [comment]
Has been merged to master
