### ISSUE TITLE
deployVerticleAwait does not have all method overloads

### ISSUE THREAD

**Issue by oripwk** [vert-x3/vertx-lang-kotlin#104]
`deployVerticleAwait()` has only the `(String)` and `(String, DeploymentOptions)` overloads, while the original method has 12 overloads.

Is this need intended?

**Comment by okou19900722** [comment]
It is generated by codegen, it will generate from only the method which type of the last parameter `Handler`

**Comment by oripwk** [comment]
This is not true. There are some overloads _with_ handler that do not have an equivalent in the `…Await()` variant. This for example:

https://github.com/eclipse-vertx/vert.x/blob/0cf14154b32f09accd19d71d76268e644a19c17c/src/main/java/io/vertx/core/Vertx.java#L384

**Comment by okou19900722** [comment]
it's annotated by @GenIgnore

**Comment by okou19900722** [comment]
it's easy to create a extension with `awaitResult`: 
```kotlin
suspend fun Vertx.deployVerticleAwait(verticleClass : KClass<out Verticle>, options : DeploymentOptions) : String {
    return awaitResult { 
        this.deployVerticle(verticleClass.java, options, it)
    }
}
```

**Comment by vietj** [comment]
I think that this proejct could handle @GenIgnore(GenIgnore.PERMITTED_TYPE) like in RxJava to allow such methods.

I will open an issue

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-lang-kotlin/issues/105
