### ISSUE TITLE
Implement @GenIgnore(GenIgnore.PERMITTED_TYPE)

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-kotlin#105]
The lesser restricted `@GenIgnore(GenIgnore.PERMITTED_TYPE)` could be implemented in Kotlin as it can handle Java types. This would allow `@GenIgnore(GenIgnore.PERMITTED_TYPE)` methods to be suspendable methods.

**Comment by okou19900722** [comment]
I will do it

**Comment by okou19900722** [comment]
it's done
