### ISSUE TITLE
Extension methods generated in the wrong package

### ISSUE THREAD

**Issue by gmariotti** [vert-x3/vertx-lang-kotlin#107]
Coroutines extensions for `io.vertx.ext.eventbus.bridge.tcp.TcpEventBusBridge` and `io.vertx.ext.eventbus.bridge.tcp.BridgeEvent` are generated in the package `io.vertx.ext.kotlin` instead of `io.vertx.kotlin.ext`.

You have better knowledge than me on the code generation, do you want to look into it @okou19900722?

**Comment by okou19900722** [comment]
https://github.com/vert-x3/vertx-tcp-eventbus-bridge/blob/master/src/main/java/io/vertx/ext/eventbus/bridge/tcp/package-info.java

the groupPackage of Modulegen in vertx-tcp-eventbus-bridge is 'io.vertx.ext '

**Comment by gmariotti** [comment]
Looking at other libraries, it doesn't seem correct. Is that the expected `groupPackage` @vietj?
