### ISSUE TITLE
MongoClient findOneAwait

### ISSUE THREAD

**Issue by dolb** [vert-x3/vertx-lang-kotlin#116]
https://github.com/vert-x3/vertx-lang-kotlin/blob/13b71682c0b547d9a113bbbe7d95cfad13769250/vertx-lang-kotlin/src/main/kotlin/io/vertx/kotlin/ext/mongo/MongoClient.kt#L228

This method can return null (if the document is not present for given query) so the return type should be : JsonObject ? for this method (and maybe some others).

**Comment by okou19900722** [comment]
it's generated from `vertx-mongo-client`, so you can annotate `@Nullable` on the type to fix it in `vertx-mongo-client` . like this [issues](https://github.com/vert-x3/vertx-redis-client/pull/116/files)

https://github.com/vert-x3/vertx-mongo-client/blob/8fdf4758fcc358d848c698a06a44159f9e9381dc/src/main/java/io/vertx/ext/mongo/MongoClient.java#L304

**Comment by vietj** [comment]
@okou19900722 is right, open an issue with a patch in mongo and this will be fixed as side effect. It can be in 3.6.3 I think.

**Comment by gmariotti** [comment]
@dolb #118 should have the Kotlin part fixed
