### ISSUE TITLE
HttpClient.kt file not present in JCenter repo

### ISSUE THREAD

**Issue by gshah30** [vert-x3/vertx-lang-kotlin#119]
If I download [vertx-lang-kotlin 3.6.2 from github](https://github.com/vert-x3/vertx-lang-kotlin/releases), I can find the file [HttpClient.kt](https://github.com/vert-x3/vertx-lang-kotlin/blob/master/vertx-lang-kotlin/src/main/kotlin/io/vertx/kotlin/core/http/HttpClient.kt). 

But since my gradle project downloads it from JCenter, I cannot import functions from HttpClient.kt as it is not present in [vertx-lang-kotlin 3.6.2 in JCenter](https://jcenter.bintray.com/io/vertx/vertx-lang-kotlin/3.6.2/).

Why is there a difference between the codebase of the same version on github and JCenter.

How do I import the functions from HttpClient.kt in my project?

Thanks.

**Comment by okou19900722** [comment]
Are you sure that there is an `HttpClient.kt` file in the release package of github download? 

The current `HttpClient.kt` is available in `4.x`.

**Comment by gshah30** [comment]
Very sorry, I guess I had multiple folders downloaded on my desktop and I looked into the wrong folder. Everything is as expected.

Sorry for bothering you guys. Closing this.
