### ISSUE TITLE
Incorrect documentation for xxxAwait methods derived from fluent methods

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-lang-kotlin#121]
The issue was originally filed in the Vert.x Cassandra Client repository https://github.com/vert-x3/vertx-cassandra-client/issues/23

Consider the following fluent and async method:

```java
  /**
   * Connect to a Cassandra service.
   *
   * @param connectHandler handler called when asynchronous connect call ends
   * @return current Cassandra client instance
   */
  @Fluent
  CassandraClient connect(Handler<AsyncResult<Void>> connectHandler);
```

When the corresponding `connectAwait` method is generated, the return type is no longer `CassandraClient`, but the kdoc is misleading:

```
suspend fun CassandraClient.connectAwait(): Unit
Connect to a Cassandra service.

Parameters
connectHandler - handler called when asynchronous connect call ends

Returncurrent
Cassandra client instance *
```

**Comment by gmariotti** [comment]
Thanks @tsegismont, it's actually a problem with all the extension methods, as far as I know. I need to invest some time before 3.7 and come up with a proper strategy for the doc

**Comment by gmariotti** [comment]
Using `CassandraClient.execute(String, Handler<AsyncResult<ResultSet>>)` as an example, I think we should try to generate something like this

```
/**
 * Suspending extension method of [io.vertx.cassandra.CassandraClient.execute]
 *
 * @param query the query to execute
 * @return ResultSet or throws an exception if the call fails
 *
 * NOTE: This function has been automatically generated from the [io.vertx.cassandra.CassandraClient] using Vert.x codegen.
 */
```
This has the advantage that it makes easy for a user to navigate to the method the extension refers to.

My main question is, can we easily figure out `T` when the last parameter of a function is of type `Handler<AsyncResult<T>>`?

**Comment by okou19900722** [comment]
yes , the generated methods signature with a return type
