### ISSUE TITLE
Create documentation/examples for generated Data Object functions

### ISSUE THREAD

**Issue by gmariotti** [vert-x3/vertx-lang-kotlin#122]

**Comment by tsegismont** [comment]
@gmariotti can you clarify the purpose of this issue? There is KDoc for both suspending extension methods and data objects (eg https://vertx.io/docs/kdoc/vertx/io.vertx.kotlin.ext.auth.jdbc/jdbc-auth-options-of.html)

**Comment by gmariotti** [comment]
Quite an old issue, but I was probably referring to have something in the repository or, even better, in the Vert.x docs with examples of the generated code. Unless you check the code or the KDoc, I don't think you can find references to the extension methods and the data classes

**Comment by tsegismont** [comment]
Thanks for clarifying. I believe we could do something similar to what we have for the Rxified API:

https://vertx.io/docs/vertx-rx/java2/

Then in module docs, have extra sections for Kotlin API:
https://vertx.io/docs/vertx-cassandra-client/java/#_rxjava_2_api

This would fit in the next gen of the website, I think.
