### ISSUE TITLE
Delegate Properties

### ISSUE THREAD

**Issue by okou19900722** [vert-x3/vertx-lang-kotlin#129]
I have an idea which learned comes from gradle.
We can write some extension function to implements delegate a properties. It's like this:
```kotlin
val key : String by json
```
it's same with this code 
```kotlin
val value = json.getString("key")
```

also we can do it in other container, like `Context`, `MultiMap` or `Session` etc...

**Comment by gmariotti** [comment]
It seems like a really cool idea. Looking at [Property Delegate Requirements](https://kotlinlang.org/docs/reference/delegated-properties.html#property-delegate-requirements) it is possible to do it by using extension functions. However, I'm not sure if these extensions can be autogenerated. Do you have already a plan on how you want to implement it?
