### ISSUE TITLE
Disambiguate toChannel() name clash

### ISSUE THREAD

**Issue by bergmanngabor** [vert-x3/vertx-lang-kotlin#134]
The extension functions `ReadStream<T>.toChannel(vertx)` and `WriteStream<T>.toChannel(vertx)` (note the omission of the optional `capacity` parameter) are in a name clash for receiver classes that are both Read+Write streams (notably `AsyncFile`).

They can be disambiguated by, for instance, renaming them to `ReadStream<T>.toReceiveChannel(vertx: Vertx)` and `WriteStream<T>.toSendChannel(vertx: Vertx)`, respectively.

**Comment by gmariotti** [comment]
I wasn't aware of this case. I think we can probably do it by deprecating with a warning the old methods and remove them in Vert.x 4. Would do you like to open a PR for it?
