### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by gmariotti** [vert-x3/vertx-lang-kotlin#140]
This is an umbrella issue for looking into deprecated methods in preparation for the next Vert.x version.

From `warning` to `error`
- [ ] `JsonArray(..)` and `JsonObject(..)`
- [ ] All data object builders with signature `DataObject(..)`

From `error` to `hidden`
- [ ] `ReceiveChannelHandler.cancel` extensions

**Comment by tsegismont** [comment]
@gmariotti @vietj moving this one to 4.0 has it would be, IMO, disturbing for users to have code broken on such a bugfix release.

@gmariotti given most users recompile the application when upgrading dependency, I would simply remove the deprecated methods in 4.0.
