### ISSUE TITLE
Missing Eventbus.sendAwait

### ISSUE THREAD

**Issue by wusatosi** [vert-x3/vertx-lang-kotlin#149]
as seen in the vert.x master branch 
https://github.com/eclipse-vertx/vert.x/blob/59f9e1798497d841c25fd434d9b9894ab7a07fd9/src/main/java/io/vertx/core/eventbus/EventBus.java#L48

Eventbus.send method still exists, though in the latest generated code, it does not 
https://github.com/vert-x3/vertx-lang-kotlin/blob/245cc8fa94b02e8d16b563cdc13acceb85f5ae02/vertx-lang-kotlin/src/main/kotlin/io/vertx/kotlin/core/eventbus/EventBus.kt#L23-L53

I did not found any documentation related to this, is it a bug or an undocumented change? Did I miss something?

The commit that removes `Eventbus.sendAwait`:
https://github.com/vert-x3/vertx-lang-kotlin/commit/245cc8fa94b02e8d16b563cdc13acceb85f5ae02#diff-834d62265d8f6018ce2cc610d5f9c407L32

**Comment by vietj** [comment]
that's weird it should not have been removed when regenerating code

**Comment by vietj** [comment]
that's only for master ?

**Comment by vietj** [comment]
actually this is what is expected, send is deprecated in 3.8 and removed in Vert.x 4.0 in favour of `request` so you should use instead `requestAwait`

**Comment by vietj** [comment]
the send method you see in EventBus is fire and forget, the `send(String, Object, Handler)` has been removed  in favor of `request`, see https://github.com/vert-x3/wiki/wiki/4.0.0-Deprecations-and-breaking-changes#%EF%B8%8F-eventbus-request-response-send-is-removed

**Comment by wusatosi** [comment]
> the send method you see in EventBus is fire and forget, the `send(String, Object, Handler)` has been removed in favor of `request`, see https://github.com/vert-x3/wiki/wiki/4.0.0-Deprecations-and-breaking-changes#%EF%B8%8F-eventbus-request-response-send-is-removed

Ok, thanks for pointing that out 😺
 
It was really confusing for me when I was figuring out this, and I believe it has been or will be really confusing for others as well 😕, can you please
-  update related documentations at https://vertx.io/docs/kdoc/vertx/io.vertx.kotlin.core.eventbus/io.vertx.core.eventbus.-event-bus/send-await.html
- add an `@Deprecated` to send method in vert.x master branch
- consider add back this method in this repo with an `@deprecated` annotation, since vertx-lang-kotlin is still in version 3.8.x and this removal will break a lot code. (as you said ` send is deprecated in 3.8 and removed in Vert.x 4.0 `)

Just  some suggestions, thanks for the support and this awesome project!
Thanks :D

**Comment by wusatosi** [comment]
> that's only for master ?

That was in release 3.7.1
