### ISSUE TITLE
Optional message parameter on EventBus.requestAwait extension functions

### ISSUE THREAD

**Issue by wem** [vert-x3/vertx-lang-kotlin#154]
Vertx: 3.8.1

Currently the extension functions EventBus.requestAwait have declared non-null message parameter. This should be optional, or even have null as default. Otherwise, it's not possible to send events without body.

**Comment by gagarski** [comment]
I came to say that there are nullability issues not only with `requestAwait` but also with `HttpRequest.sendJsonAwait` and `HttpRequest.sendJsonableAwait` from vertx-web (at least, maybe also somewhere else). But I found out that vertx web client does not deal with `null` JSON values correctly. See https://github.com/vert-x3/vertx-web/issues/1436. 

Nullability for these functions should also be fixed when the issue with the web client is resolved.

**Comment by vietj** [comment]
it seems that we should annotate the request parameter with `@Nullable` in event bus right ?

**Comment by gagarski** [comment]
Yeah it probably should fix it for `EventBus.requestAwait` and `HttpRequest.sendJsonAwait`/`HttpRequest.sendJsonableAwait`.

**Comment by wem** [comment]
IMHO would be the better way to solve Kotlin issues the Kotlin way with nullable parameters like: 
`suspend fun <T> EventBus.requestAwait(address: String, message: Any? = null): Message<T> {
  return awaitResult {
    this.request(address, message, it)
  }
}`
So it's even not necessary to pass "null" the those functions.
If that is okay for you, i will do a PR for all here functions listed here.

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/3199
