### ISSUE TITLE
Look we can't register jackson-kotlin module in Vert.x new version

### ISSUE THREAD

**Issue by cpdyj** [vert-x3/vertx-lang-kotlin#155]
Are there any way to register jackson-kotlin module in Vert.x again? If not, should we register it automatically?

**Comment by vietj** [comment]
you can register modules using `io.vertx.core.json.jackson.mapper()` and `io.vertx.core.json.jackson.prettyMapper()`

**Comment by cpdyj** [comment]
@vietj thank you（

**Comment by cpdyj** [comment]
> you can register modules using `io.vertx.core.json.jackson.mapper()` and `io.vertx.core.json.jackson.prettyMapper()`

fix: It's `io.vertx.core.json.jackson.DatabindCodec.mapper()`
