### ISSUE TITLE
Web Client Kotlin docs use "as" without escaping

### ISSUE THREAD

**Issue by tobiasmuehl** [vert-x3/vertx-lang-kotlin#156]
From https://github.com/vert-x3/vertx-web/issues/1444

The example code on handling JSON responses on https://vertx.io/docs/vertx-web-client/kotlin/#_handling_http_responses is syntactically incorrect in Kotlin.

`client.get(8080, "myserver.mycompany.com", "/some-uri").as(BodyCodec.jsonObject()).send({ ar ->`

should be 

```
client.get(8080, "myserver.mycompany.com", "/some-uri").`as`(BodyCodec.jsonObject()).send({ ar ->
```

**Comment by tsegismont** [comment]
Closing, we no longer generate Kotlin examples from Java code
