### ISSUE TITLE
Document using vertx-lang-kotlin-gen to generate suspending methods

### ISSUE THREAD

**Issue by rgmz** [vert-x3/vertx-lang-kotlin#159]
A faux pas on my part, but I have been using Vert.x with Kotlin Coroutines (💖) for almost a year and only just realized that it's possible to generate suspending methods for my own project.

[The documentation mentions that](https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/#_suspending_extension_methods):
> ...Vert.x generates suspending extension methods for all its asynchronous methods.

But it should mention the use of `vertx-lang-kotlin-gen` with kapt as well.

---

**Gradle**
```
dependencies {
  kapt "io.vertx:vertx-lang-kotlin-gen:$vertxVersion"
  ...
}
```

**Maven**
https://kotlinlang.org/docs/reference/kapt.html#using-in-maven
Include `vertx-lang-kotlin-gen` as an `annotationProcessorPath`:
```
<annotationProcessorPath>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-lang-kotlin-gen</artifactId>
  <version>${vertx.version}</version>
</annotationProcessorPath>
```

**Comment by dangfan** [comment]
Hi @rgmz , I've added the `vertx-lang-kotlin-gen` in my gradle file. Here is some of my interface:

```
@ProxyGen
@VertxGen
public interface LiveDatabaseService {
  @Fluent
  LiveDatabaseService createLiveEntry(String streamName, Handler<AsyncResult<Long>> resultHandler);
```

But it didn't generate the corresponding `Await` methods in the `generated` path. Did I miss anything?

Thanks!

**Comment by rgmz** [comment]
> But it didn't generate the corresponding `Await` methods in the `generated` path. Did I miss anything?

@dangfan Is `vertx-codegen` also defined for kapt?
```
kapt "io.vertx:vertx-codegen:$vertxVersion"
```

**Comment by dangfan** [comment]
> > But it didn't generate the corresponding `Await` methods in the `generated` path. Did I miss anything?
> 
> @dangfan Is `vertx-codegen` also defined for kapt?
> 
> ```
> kapt "io.vertx:vertx-codegen:$vertxVersion"
> ```

Yes, my `build.gradle` is like this:

```

**Comment by Anillc** [comment]
I also encountered this problem. The log of the generator was `Non future method cn.anillc.projbot.ProjBot: cn.anillc.projbot.ProjBot start(io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>> handler)`. I don't understand the meaning of it. Is there any wrong in my method defination?

**Comment by vietj** [comment]
note that in vert.x 4 we still allow but discourage generating suspending methods. Service proxies in a next release will allow to write the service using futures instead of callback and that works nicely with coroutines

**Comment by vietj** [comment]
that might be the reason why we would not add it to the documentation.

**Comment by hbrackel** [comment]
Why would a future generator not generate kotlinesque suspending methods? A typical "reactive" interface in Kotlin looks like

suspend fun doSomething(param1:T) : S
or
fun doSomethingStreaming(param2:R) : Flow<S>

Their behind the scenes implementation could still call await() on a future. Otherwise, another manual API layer would be needed to get a convenient Kotlin API (calling .await() is possible but not really the Kotlin way - which is NOT to expose futures)

**Comment by vietj** [comment]
because now vertx method return a future and you can write

somethinAsync().await()

instead of

somethingAsyncAwait()

so we prefer to avoid generating such code in practice.

Of course service-proxies cannot do that yet (they need to use Handler) but
in 4.1 we would like to have service proxies able to return a Future

**Comment by hbrackel** [comment]
when using the vertx API calls to do sequential  processing, as in
```
launch(vertx.dispatcher()){
    val a = doFirstThing() // eventbus call
    val b = doSecondThing(a) // evenbus call
}
```
you would want suspending functions. You could certainly also write (in case of futures)
```
launch(vertx.dispatcher()){
    val a = doFirstThing().await() // eventbus call
    val b = doSecondThing(a).await() // evenbus call
}
```
but this doesn't provide the best Kotlin experience (at least not IMO)

**Comment by vietj** [comment]
so you are saying taht we should continue supporting the generation of
extension methods for coroutines ?

**Comment by rgmz** [comment]
> so you are saying taht we should continue supporting the generation of extension methods for coroutines ?

It's worth noting that the Kotlin team prefers `.await()` extension methods over things like `...methodAwait()` or `...methodAsync()`. 

https://www.youtube.com/watch?v=_hfBv0a09Jc

**Comment by hbrackel** [comment]
For all of my vertx use cases (I exclusively use Kotlin) I'd vote for coroutine extension methods. The option of calling .await() on futures still remains available as one can use the generated Java code from Kotlin as well.

A little of topic, so just a quick mention: it would also be very nice to have a suspend handle() method option similar to the start() and start(future) available in the service stub. The handle() method usually also processes steps sequentially.

**Comment by vietj** [comment]
I'm open to anything :-)

I believe that for Vert.x code we want to remove generation and have ppl
use .await()

but for users, I believe we should give them freedom to chose.

**Comment by hbrackel** [comment]
> > so you are saying taht we should continue supporting the generation of extension methods for coroutines ?
> 
> It's worth noting that the Kotlin team prefers `.await()` extension methods over things like `...methodAwait()` or `...methodAsync()`.
> 
> https://www.youtube.com/watch?v=_hfBv0a09Jc

That's absolutely true - for async calls

**Comment by rgmz** [comment]
> > > so you are saying taht we should continue supporting the generation of extension methods for coroutines ?
> > 
> > 
> > It's worth noting that the Kotlin team prefers `.await()` extension methods over things like `...methodAwait()` or `...methodAsync()`.
> > https://www.youtube.com/watch?v=_hfBv0a09Jc
> 
> That's absolutely true - for async calls

Indeed.

@hbrackel out of curiosity, are you using Vert.x purely with Kotlin or relying on things like Service Proxies?

I tend to [only use Kotlin + Kotlin Coroutines, and avoid `@VertxGen` whenever possible](https://groups.google.com/g/vertx/c/T_InzpwD6Ro/m/PrlMaQYNCwAJ).

Therefore, my code tends to be normal classes with `suspend` methods wrapped in `coroutineScope`:
```kotlin
// MainVerticle.kt
class MainVerticle : CoroutineVerticle() {
  
  override suspend fun start() {
     super.start()

    val client = Client(vertx)
    println("Result is '${client.foo()}'")
  }
}

// Client.kt
class Client(private val vertx: Vertx) : CoroutineScope by CoroutineScope(vertx.dispatcher()) {
  suspend fun foo(): String = coroutineScope {
    // normal code written like kotlin Coroutines
    println("Doing thing...")
    delay(1000L)
    "bar"
   }
}
```

**Comment by hbrackel** [comment]
@rgmz at this time, I write all code the same way as you do, exclusively Kotlin, no `@VertxGen`. But as I am dealing with many verticle based services, I am a little tired of the boilerplate (particularly on the server / handler side; message composition, error handling, ...) plus I'd like to use the (vertx) service discovery. I did not see any benefit in using the Vertx code gen feature, because the Kotlin API didn't look like I needed or wanted it.
I also use most of the vertx services in conjunction with Spring and would appreciate a similar reactive API (see above) to access services, irrespectively of their implementation

**Comment by tsegismont** [comment]
Closing: Vert.x does not generate `xxxAwait` methods anymore.
