### ISSUE TITLE
why executeBlockingAwait return type is nullable?

### ISSUE THREAD

**Issue by rainmanhhh** [vert-x3/vertx-lang-kotlin#160]
executeBlockingAwait calls awaitResult
If awaitResult failed, it will throw an exception instead of return null
The return type should be [T] but not [T?]

**Comment by rgmz** [comment]
I don't see `null` as synonymous with failure; some methods have [`@Nullable`](https://github.com/vert-x3/vertx-codegen/blob/master/src/main/java/io/vertx/codegen/annotations/Nullable.java) results, for example:
* [`io.vertx.redis.client.RedisAPI`](https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/client/RedisAPI.java#L54-L57)
    ```java
    default RedisAPI append(String arg0, String arg1, Handler<AsyncResult<@Nullable Response>> handler) {
      send(Command.APPEND, arg0, arg1).setHandler(handler);
      return this;
    }
    ```
* [`io.vertx.kotlin.redis.client`](https://github.com/vert-x3/vertx-lang-kotlin/blob/396be85eabf397c647b3f7dc934a0622aa237556/vertx-lang-kotlin/src/main/kotlin/io/vertx/kotlin/redis/client/RedisAPI.kt#L31-L35)
    ```kotlin
    suspend fun RedisAPI.appendAwait(arg0: String, arg1: String): Response? {
      return awaitResult {
        this.append(arg0, arg1, it)
      }
    }
    ```

**Comment by rainmanhhh** [comment]
NOTE: the parameter is <T> but not <T: Any>
so if the action return value is actually nullable(eg. <Response?>), just call it like this:
executeBlockingAwait<Response?>(...)
<Response?> can be omitted

**Comment by tsegismont** [comment]
The return type is `T?` because when the call succeeds, the result can be `null`.
