### ISSUE TITLE
 vertx-web-openapi does not seem to be instrumented for kotlin

### ISSUE THREAD

**Issue by gdurandrexel** [vert-x3/vertx-lang-kotlin#176]
For instance it misses RouterFactory.createAwait and helpers for options.
Seen in Beta1.

**Comment by tsegismont** [comment]
@pk-work would you mind taking care of this? Is it possible?

**Comment by pk-work** [comment]
Of course, I will try to help. But I never added kotlin support before, what do I have to do? @babsher Do you have questions? I could try to answer them.

**Comment by tsegismont** [comment]
There's a checklist for integration of a module in the stack: https://github.com/vert-x3/vertx-stack#adding-a-new-module-to-the-stack

The Kotlin binding generation is one of the points

**Comment by pk-work** [comment]
I guess this will be fixed with the next release?
