### ISSUE TITLE
PgPool/Coroutine exception swallowed

### ISSUE THREAD

**Issue by adandersen** [vert-x3/vertx-lang-kotlin#177]
### Version

Which version(s) did you encounter this bug ?

3.9.0, also tried 3.9.2

### Context

pasted in part from from the [google group](https://groups.google.com/g/vertx-dev/c/2u1kx02jWD4).

When a certain type of postgres error occurs, the exception isn't propagated and is not catchable. I'm not exactly sure why, perhaps its the interplay of a few libraries. This happens when calling a suspend function that has awaitResult with coroutines.

If you change the sql in a minor way from my below example, say, to a table name that doesn't exist, the error propagates fine.

### Do you have a reproducer?

[reproducer here](https://github.com/adandersen/vertx-coroutine-swallowed-exception)

### Steps to reproduce

1) run the ./createdb.sh to create example database with empty table
2) enter password to postgres
3) run main project and see error

The error is a type mismatch error, and the code indicated by [this link](https://github.com/eclipse-vertx/vertx-sql-client/blob/475dda57129adb8555f8eb09f2c3dbaa3c10eb02/vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/ErrorMessageFactory.java#L23) is a good place to put a breakpoint to see a stacktrace.

### Extra

Julien speculated that it might be because of the NoStackTraceThrowable, and suggested wrapping the message in a VertxException, which did propagate the error then.

e.g. `handler.handle(Future.failedFuture(new VertxException(msg)));` on line 74 in PreparedStatementImpl in version 3.9.0.

I'm not sure what the ramifications are of doing that or what other places this might need to change as well.

**Comment by gaojinlei** [comment]
I have the same problem on using vertx-pg-client in vertx-4.0.0-CR1. When pg-client throws a NoStackTraceThrowable, try-catch clause cannot capture the exception  . With analysis the source code of NoStackTraceThrowable class:
```java
public class NoStackTraceThrowable extends Throwable {
    public NoStackTraceThrowable(String message) {
        super(message, (Throwable)null, false, false);
    }
}

// super constructor
protected Throwable(String message, Throwable cause,
                        boolean enableSuppression,
                        boolean writableStackTrace) {
        if (writableStackTrace) {
            fillInStackTrace();
        } else {
            stackTrace = null;
        }
        detailMessage = message;
        this.cause = cause;
        if (!enableSuppression)
            suppressedExceptions = null;
    }
```
it's casue is null and writableStackTrace is false so try-catch clause cannot deal with this.
It seems like that many methods in vertx libraries throw NoStackTraceThrowable when future result faild. I have to use composed future now. So is there a graceful solution to deal with this

**Comment by okou19900722** [comment]
hi, you should catch Throwabe instead of Exception.
cause of that NoStackTraceThrowable is a subclass of Throwable, not Exception. Exception is also a subclass of Throwable
