### ISSUE TITLE
Closure interoperability with Handler

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-lang-kotlin#18]
Hello,

I'm often finding myself stuck with this kind of stuff : 

```kotlin
    @Before
    fun setup(ctx: TestContext) {
        vertx.executeBlocking<Void>( { fut: Future<Void> ->
            // blocking stuff
            fut.complete()
        }, ctx.asyncAssertSuccess())
    }
```

This code doesn't compile because the first closure cannot be understood as a `Handler<Future<Void>>`

The compiling equivalent would be :

```kotlin
    @Before
    fun setup(ctx: TestContext) {
        vertx.executeBlocking<Void>( Handler { fut: Future<Void> ->
            // blocking stuff
            fut.complete()
        }, ctx.asyncAssertSuccess())
    }
```

Is there a way to avoid the `Handler { ` stuff ? Is this a kotlin limitation ?

In every other language, scala included, a lambda is a valid replacement for a `Handler` can we do something about this ?

Thanks.

**Comment by vietj** [comment]
is it still needed ? I've been able to write kotlin code without the need of an adapter.
