### ISSUE TITLE
completionHandlerAwait alternative completionHandler().await() is missing

### ISSUE THREAD

**Issue by wem** [vert-x3/vertx-lang-kotlin#190]
The alternative of the deprecated completionHandlerAwait is currently missing.

### Version

Vert.x 4

### Workaround

I solved it with an own extension function.

```
fun <T> MessageConsumer<T>.completionHandler() : Future<Void> {
    val promise = Promise.promise<Void>()
    completionHandler { promise.handle(it) }
    return promise.future()
}
```

**Comment by vietj** [comment]
I think we should have a completion() method in MessageConsumer that returns a Future along with a completion(Handler<AsyncResult>). The main reason is that completionHandler returning a Future does not make much sense.

**Comment by wem** [comment]
Will do the work for that.

**Comment by tsegismont** [comment]
In https://github.com/eclipse-vertx/vert.x/pull/4645, a `MessageConsumer#completion()` method has been added.

It returns a `Future` on which `await()` can be invoked
