### ISSUE TITLE
Starting a coroutine on a vert.x worker thread runs it on the same thread but should hand it over to the event loop thread

### ISSUE THREAD

**Issue by bbyk** [vert-x3/vertx-lang-kotlin#217]
### Questions

Starting a coroutine on a vert.x worker thread ends up running it inline, that is on the very same thread, instead of the event loop thread. This seems like a bug because it contradicts the KDoc on [Context.dispatcher()](https://github.com/vert-x3/vertx-lang-kotlin/blob/master/vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/VertxCoroutine.kt#L145-L151)

### Version

vert.x 4.1.5, kotlin 1.5.31, coroutines 1.5.2

### Context

[VertxCoroutineExecutor](https://github.com/vert-x3/vertx-lang-kotlin/blob/master/vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/VertxCoroutine.kt#L223-L231)

```
private class VertxCoroutineExecutor(val vertxContext: Context) : AbstractExecutorService(), ScheduledExecutorService {

  override fun execute(command: Runnable) {
    if (Vertx.currentContext() != vertxContext) {
      vertxContext.runOnContext { command.run() }
    } else {
      command.run()
    }
  }
```
I suspect the code might be lacking a check for `isOnWorkerThread` e.g. the if-statement should look like:

```
if (Vertx.currentContext() != vertxContext || Context.isOnWorkerThread()) {
      vertxContext.runOnContext { command.run() }
```

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/72110/150617291-d65990d8-4823-41ec-9e41-8425af5f3720.png">

### Do you have a reproducer?

```
            awaitBlocking {
                launch {
                    println(Thread.currentThread().name)
                }
            }
```

Prints
```
vert.x-worker-thread-0 @coroutine#23
```

**Comment by tsegismont** [comment]
I think the behavior is right but the doc is wrong.

The purpose of `io.vertx.kotlin.coroutines.VertxCoroutineKt#dispatcher(io.vertx.core.Context)` is to launch coroutines on the corresponding context. And inside `awaitBlocking`, we're still on the same Vert.x context (but on a worker thread).

**Comment by tsegismont** [comment]
If that's fine with you @vietj , I'll update the doc

**Comment by tsegismont** [comment]
In fact, this was indeed a bug, which has been fixed by https://github.com/vert-x3/vertx-lang-kotlin/pull/237
