### ISSUE TITLE
Upgrade to 4.4.0 requires stdlib 

### ISSUE THREAD

**Issue by hantsy** [vert-x3/vertx-lang-kotlin#231]
When upgrading my sample from 4.3.8 to 4.4.0, I have to add `kotlin-stdlib` to make it work, https://github.com/hantsy/vertx-sandbox/blob/5d5a18a168d13701a36d703183787d0b3af85fcd/kotlin/pom.xml#L54

Is the `kotlin-stdlib` not a dep of `verxt-lang-kotlin` since 4.4.0?

**Comment by tsegismont** [comment]
@hantsy right, this is a consequence of #227

`kotlin-stdlib` is not strictly required by the project. I wonder if there's a reason why we should include it.

Any suggestion @AlexeySoshin ?

**Comment by hantsy** [comment]
No need kotlin-stdlib-jdk8, kotlin-stdlib-jdk7 etc., the kotlin-stdlib includes them.

**Comment by vincentfree** [comment]
For kotlin based projects it should at least be in with provided scope. A kotlin project can't function without it but this library doesn't need to set the library version since a typical project includes it.

**Comment by tsegismont** [comment]
Fixed by 26bf045
