### ISSUE TITLE
Generated source code should respect Vert.x code style guidelines

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-kotlin#3]
https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

**Comment by napperley** [comment]
Also important that the generated source code follows the official [Kotlin Code Conventions](https://kotlinlang.org/docs/reference/coding-conventions.html).

**Comment by tsegismont** [comment]
Outdated, generated source code respects Vert.x code style guidelines
