### ISSUE TITLE
Wrong vertx-lang-kotlin-coroutines name in docs

### ISSUE THREAD

**Issue by ufoscout** [vert-x3/vertx-lang-kotlin#34]
In the documentation (e.g. index.adoc file) the `vertx-lang-kotlin-coroutines` module is always indicated as `vertx-lang-kotlin-coroutine` (without the the 's' at the end) creating lots of confusion when you try to import it in your project.

**Comment by vietj** [comment]
thanks will update the onlline version as well

**Comment by vietj** [comment]
it has been updated online as well, thanks for reporting !
