### ISSUE TITLE
Investigate usefulness of code generation for Kotlin coroutines

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-kotlin#41]
for instance, now we use the `await*` suspending function like this

```
val id = awaitEvent<Long> { vertx.setTimer(1000, it) }
```

we could generate extensions:

```
suspend fun Vertx.setTimer(delay: Long): Long {
  return awaitEvent<Long> { setTimer(delay, it) }
}
```

that allow to directly write:

```
val id = vertx.setTimer(1000)
```

**Comment by stream1984** [comment]
LGTM :)
by the way, the last line is 

val id = **V**ertx.setTimer(1000)

**Comment by vietj** [comment]
actually no, this is Kotlin and that's an extension method that is available on vertx instances.

**Comment by stream1984** [comment]
It's true, my fault. 😅

**Comment by CoreyKaylor** [comment]
This would be very preferential. There are many areas that callbacks in vertx api could be translated to coroutine suspension function and IMO would make it more idiomatic kotlin and simpler for those approaching vertx as well.

**Comment by feiyanke** [comment]
It is useful if working with coroutine. Is this code generator done by [vertx-codegen](https://github.com/vert-x3/vertx-codegen)?

**Comment by vietj** [comment]
@feiyanke yes, it is currently implemented for data object and Kotlin in this project

**Comment by phiSgr** [comment]
I have spent the long weekend to come up with this pull request #53 .
The code is quite hacky for now though. 😕

Would anyone mind reviewing before I continue?

**Comment by tsegismont** [comment]
Closing as outdated, coroutines support has been implemented
