### ISSUE TITLE
Integrate classes from https://github.com/cy6erGn0m/vertx3-lang-kotlin

### ISSUE THREAD

**Issue by Yoshi3003** [vert-x3/vertx-lang-kotlin#45]
Hi, thanks for this great Korlin integration.

However, I still notice that https://github.com/cy6erGn0m/vertx3-lang-kotlin, there are some classes (i.e. AsyncResult) that are still not available when just using this module. I need to include both `vertx3-lang-kotlin` and `vertx-lang-kotlin` to get the most out of Kotlin-style integration. The readme in https://github.com/cy6erGn0m/vertx3-lang-kotlin says that 

> vertx3-lang-kotlin is going to be moved into vert.x organization: https://github.com/vert-x3/vertx-lang-kotlin/

But it has been like that for a very long time now. Is there any plan to do such thing at all ? That would be superb.

Thank you.

**Comment by vietj** [comment]
the https://github.com/cy6erGn0m/vertx3-lang-kotlin is replaced by this project, so the documentation in this repo is not actual.

what are you trying to achieve ?

**Comment by Yoshi3003** [comment]
@vietj Thanks for your response. There are some classes that I cannot find when just using this project. For example, https://github.com/cy6erGn0m/vertx3-lang-kotlin/blob/master/src/main/kotlin/io/vertx/kotlin/lang/async-result.kt.
