### ISSUE TITLE
kotlin version 

### ISSUE THREAD

**Issue by psartini** [vert-x3/vertx-lang-kotlin#46]
3.5.1-SNAPSHOT will ship with version 1.2.20 of kotlin. see #44 
Latest version as of today is 1.2.21.

It would be great if we were able to specify the kotlin version in our projects. 
Right now, I am excluding kotlin dependencies from vertx-lang-kotlin:

>compile(group = "io.vertx", name = "vertx-lang-kotlin", version = vertx_version) {
>        exclude(group = "org.jetbrains.kotlin")
>}

Will this lead to incompatibilities, or is this is a reasonable way to keep kotlin version up to date?

**Comment by vietj** [comment]
that's an interesting concern, one issue we have right now is that vertx-ext-parent depends on the version of the kotlin compiler which makes upgrading kotlin a bit complicated - we hope to solve this in next versions

**Comment by vietj** [comment]
I think we could upgrade to 1.2.21 since I would like to have the latest version of the vertx-parent to be used for releasing 3.5.1

**Comment by vietj** [comment]
I don't think it would because i'ts supposed to be binary compatible. Anyway we want to change that for 3.6.0 and remove kotlin compilation from actual jars and make separate jars ilke we do for scala

**Comment by jasoet** [comment]
@vietj just create pull request to update Kotlin version https://github.com/vert-x3/vertx-lang-kotlin/pull/48

**Comment by vietj** [comment]
I think we need to really think about decoupling vertx stack modules from kotlin directly, I think it can be achieved in a simple manner

**Comment by jasoet** [comment]
@vietj you have any ideas in mind to tackle this issue? 
I think I will able to contribute

**Comment by vietj** [comment]
I've started to talk about it on the Vert.x dev google group

**Comment by vietj** [comment]
@jasoet the decoupling has been achieved in this module now you can bump the version here, see https://github.com/vert-x3/vertx-lang-kotlin

**Comment by jasoet** [comment]
@vietj thanks, will check the code and send PR

**Comment by jasoet** [comment]
@vietj I got some dependency error when building `vertx-lang-kotlin`

```
[WARNING] The POM for io.vertx:vertx-auth-htdigest:jar:3.6.0-20180301.004139-24 is missing, no dependency information available
[WARNING] The POM for io.vertx:vertx-auth-jwt:jar:3.6.0-20180301.004116-24 is missing, no dependency information available
```

```
[ERROR] Failed to execute goal on project vertx-lang-kotlin: Could not resolve dependencies for project io.vertx:vertx-lang-kotlin:jar:3.6.0-SNAPSHOT: The following artifacts could not be resolved: io.vertx:vertx-auth-htdigest:jar:3.6.0-SNAPSHOT, io.vertx:vertx-auth-jwt:jar:3.6.0-SNAPSHOT: Failure to find io.vertx:vertx-auth-htdigest:jar:3.6.0-20180301.004139-24 in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
```

**Comment by jasoet** [comment]
@vietj I see that build from Vertx Jenkins CI still failed. Anyway, I send pull request to bump Kotlin to the newest version.

https://github.com/vert-x3/vertx-lang-kotlin/pull/50

**Comment by vietj** [comment]
@jasoet there are currently issues with snapshot publishing

**Comment by vietj** [comment]
and we need to investigate them
