### ISSUE TITLE
Provide an awaitBlocking function for specific context

### ISSUE THREAD

**Issue by oripwk** [vert-x3/vertx-lang-kotlin#54]
In issue #42 a new function was added for running blocking code on the worker pool and as a coroutine.

However, the function calls `executeBlocking` internally using `Vertx.currentContext()`. This is problematic for the following reasons:
1. It make this function less modular and reusable, since it depends on global state
1. It does not allow control for the developer on which context to run the code
1. It causes problems in testing since it will always return null because the test code does not run on the event loop.

On the other hand, `executeBlocking` _does_ allow control on which context to run. `awaitBlocking` is somewhat a flavor of `executeBlocking` which works without the need to provide a future, so there's no reason it won't mirror `executeBlocking` functionality.

**Comment by n0rtan** [comment]
Do we can use coroutines itself instead?
For example, just create an extension for worker pool dispacher like that:
`
fun Vertx.workerDispatcher(): CoroutineDispatcher {
  return (this as VertxInternal).workerPool.asCoroutineDispatcher()
}
`
and use it in verticle:

`
val account = async(vertx.workerDispatcher()) {
    accountsRepository.account(Id)
}.await() ?: throw Exception("User not found")
`

or using executeBlocking is required?

**Comment by lfmunoz** [comment]
@oripwk do you have a specific use case? I have a feeling that if you need to execute blocking on some specific context you didn't structure your code correctly. Mostly you are on an eventloop and you execute blocking on the context of the eventloop.

**Comment by oripwk** [comment]
@lfmunoz I do not agree that it implies the code is not structured correctly.
* A code that uses Vert.x's default `awaitBlocking` method is not testable outside a running Vert.x app since it requires the test code to be coupled with Vert.x.
* Generally speaking (practices-wise), anything that depends on global state is not modular and makes everything harder.
* `executeBlocking` (unlike `awaitBlocking`) has a flavor where you call it on the `vertx` object itself: `vertx.executeBlocking(…)`. Why not have the same thing with `awaitBlocking`?

@vietj can you please advice?

**Comment by vietj** [comment]
@oripwk so you are suggesting in case there is no context to defer blocking on another pool like the JVM FJ pool ? `Vertx#executeBlocking` might not work because it supposed this is executed from a Vert.x thread (look at the implementation).

**Comment by oripwk** [comment]
I'm suggesting this:
```
suspend fun <T> Vertx.awaitBlocking(ordered: Boolean = false, block: () -> T): T = awaitResult { handler ->
    executeBlocking({ it.complete(block()) }, ordered, handler::handle)
}
```
