### ISSUE TITLE
Kotlin dataobject helper functions missing copy style constructor

### ISSUE THREAD

**Issue by apatrida** [vert-x3/vertx-lang-kotlin#6]
for example, `DeploymentOptions` has a constructor:

```
 public DeploymentOptions(JsonObject json) { ... }
```

and our helper function doesn't represent that.

**Comment by vietj** [comment]
what you give more info ? you can still use the orignal data object with its json contrsuctor

**Comment by tsegismont** [comment]
Closing, use the original object copy constructor.
