### ISSUE TITLE
Replicated Kotlin coroutines function

### ISSUE THREAD

**Issue by dualscyther** [vert-x3/vertx-lang-kotlin#74]
In this file:

https://github.com/vert-x3/vertx-lang-kotlin/blob/master/vertx-lang-kotlin-coroutines/src/main/java/io/vertx/kotlin/coroutines/VertxCoroutine.kt

The extension method `Future.await()` is essentially a duplicate of `CompletionStage.await()` as documented here:

https://github.com/Kotlin/kotlinx.coroutines/blob/master/integration/kotlinx-coroutines-jdk8/README.md

I assume this has happened because `CompletionStage.await()` was only added in March this year. Should the Vertx version be deprecated in favour of the official Kotlin library method?

**Comment by vietj** [comment]
vertx Future is not related to `CompletionStage`, that might be different in Vert.x 4 that will provide `CompletionStage` methods
