### ISSUE TITLE
Read PDF after post (uploadFiles)

### ISSUE THREAD

**Issue by simonext** [vert-x3/vertx-lang-kotlin#82]
Hy,

I need to read content of pdf (or png , etc ...)
The file is uploaded in the good directory, i can check it in my file system.
But when i want to read it (from vertx.fileSystem and get the buffer), the content is modified.

Can you help me ? 

thank you

Vertx version 3.5.1
Kotlin version 1.2.71

**Comment by simonext** [comment]
router.post("$rootPath//file).handler(create().setBodyLimit(config.getLong("limit.size.file"))).failureHandler { ctx -> failureHandler(ctx) }.coroutineHandler{ ctx -> file(ctx) }


private suspend fun fileEncrypt(ctx: RoutingContext) {
        val f = ctx.fileUploads()

        val fs = vertx.fileSystem()
        if (f.count() < 1) {
            ctx.fail(NoFile(ctx))
            return
        }
        if (f.count() > 1) {
            ctx.fail(TooManyFile(ctx))
            return
        }
        val fileName = f.first().uploadedFileName()
        val good = File("good.pdf")
        val bad = File("bad.pdf")
        fs.readFile(fileName) { buffer ->
            good.writeBytes(buffer.result().bytes) // this file is write good
            bad.writeText(buffer.result().toString(Charsets.UTF_8),Charsets.UTF_8)// this file is NOT write good

           // ctx.body.appendJson { obj("content" to arrayListOf(buffer.result().toString())) }
            fs.delete(fileName) {
                launch(Unconfined) {
                    doSomething(ctx,buffer.result())
                    //ctx.response().end(buffer.result())
                }
            }
        }
    }


I hope it is what you need to inspect.

Thank You

**Comment by tsegismont** [comment]
A PDF file may contain binary content, so you can't convert to text and then back to binary without altering the content.

**Comment by simonext** [comment]
Thx i did it :D
