### ISSUE TITLE
Better understanding the tests

### ISSUE THREAD

**Issue by gmariotti** [vert-x3/vertx-lang-kotlin#87]
Hi @vietj, sorry if I'm asking you here, I didn't find a better place for it. I'm trying to fix the tests connected to the `ReadStream<T>` conversion to a `Channel<T>` in the `vertx-lang-kotlin-coroutines` module.

- In line 68 of the `HttpParserTest`, when you add the chunk to the resulting body, you only append `chunk.length() - 2` instead of the entire length of the chunk read, is there any particular reason?
- In the `ReceiveChannelHandlerTest`, you create an instance of the `TestStream` class, but I wasn't able to understand the reasons why you're prefering it over an instance of `ReadStream/WriteStream`. And this actually creates some issues with the call to `fetch` on the `TestStream`. Is there something I'm missing there?

**Comment by chengenzhao** [comment]
same here
@okou19900722

**Comment by vietj** [comment]
@gmariotti 

## line 65

The `RecordParser` is used to parse HTTP, first the parser is created with `\r\n` delimiter to parse the HTTP line and headers. When the transfer encoding header is chunked it means that the parsing will use chunked encoding which sends a number that is the number of bytes to read, so we must do some math around it to include/exclude the extra `\r\n`:

```
13\r\n
Hello World\r\n
```

When the HTTP parser reads `13`, the record parser is switched to `13 + 2` to take in account the extra `\r\n` chars. When we get the chunk we drop the 2 remaining chars to only get `Hello World`.

## ReceiveChannelHandlerTest

I can't find this class.

I think that the `TestStream ` must be reimplemented to take in account the new fetch mode and honour it. Currently it throws `UnsupportedOperationException`. A similar class can be found here https://github.com/vert-x3/vertx-rx/blob/master/rx-gen/src/test/java/io/vertx/lang/rx/test/TestReadStream.java

**Comment by gmariotti** [comment]
@vietj sorry, `ReceiveChannelHandlerTest` was part of my PR refactoring. But thanks for the explanation.

**Comment by vietj** [comment]
I hope it's enough context for you, don't hesitate to ask for more.

**Comment by chengenzhao** [comment]
> @gmariotti
> 
> ## line 65
> The `RecordParser` is used to parse HTTP, first the parser is created with `\r\n` delimiter to parse the HTTP line and headers. When the transfer encoding header is chunked it means that the parsing will use chunked encoding which sends a number that is the number of bytes to read, so we must do some math around it to include/exclude the extra `\r\n`:
> 
> ```
> 13\r\n
> Hello World\r\n
> ```
> When the HTTP parser reads `13`, the record parser is switched to `13 + 2` to take in account the extra `\r\n` chars. When we get the chunk we drop the 2 remaining chars to only get `Hello World`.
> 

Hi Viet:

Above logic works fine if the chunk ends with "\r\n"
however
if the chunk doesn't ends with "\r\n" then the logic will make redundant -2 job
let's say in the unit test we have the chunk string
"abc123" sent the server and the record parser parse it but
it will provide "abc123" string to the channel
and the chunk string received would be "abc123" rather than "abc123\r\n"
thus the assert equal statement will fail for the reason "abc123" doesn't equal to "abc1"...
so I would suggest to change line 68 to 
`
if(chunk.endsWith("\r\n")) body.appendBuffer(chunk, 0, chunk.length() - 2)
else body.appendBuffer(chunk)
`

**Comment by chengenzhao** [comment]
@vietj 
chunk data requires the chunked string to be ended with "0\r\n\r\n"
but before that end string, the last line may not end with CRLF("\r\n")
I have not check Http 1.1 specification yet, but I guess that could be the case
if Http 1.1 spec. defines each line has to be ended with CRLF
then probably there is a bug in the http client chunk part implementation

@gmariotti 
https://en.wikipedia.org/wiki/Chunked_transfer_encoding
This link maybe helpful :)

**Comment by chengenzhao** [comment]
https://www.w3.org/Protocols/HTTP/1.1/rfc2616.pdf
just found it 
so each line has to be ended with CRLF

**Comment by vietj** [comment]
I think that actually the \r\n you are mentioning is actually the second trailing one in 0\r\n\r\n

0\r\n <- this is the last chunk that is empty
\r\n <- the last empty chunk
