### ISSUE TITLE
Use Kotlin 1.3

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-kotlin#88]
Kotlin 1.3 was recently released, it should be used in Vert.x 3.6 release.

**Comment by vietj** [comment]
@gmariotti interested to tackle this ?

**Comment by gmariotti** [comment]
that was my goal after reopening the previous MR 😂. More than happy to help there

**Comment by dualscyther** [comment]
Just putting this here for future reference:

https://github.com/Kotlin/kotlinx.coroutines/blob/master/COMPATIBILITY.md

**Comment by dualscyther** [comment]
@gmariotti are you working on this? I'd also be keen to help out. It might be a good time to make API improvements too since we're likely to break the API anyway given our upgrade to coroutines with the structured concurrency model.

**Comment by gmariotti** [comment]
@dualscyther not yet. I'd like to have #89 in first so that all the deprecated coroutines code is removed and then starting the migration. I quickly tried on my machine and the coroutines migration is quite simple the moment all the deprecated code is removed.

**Comment by gmariotti** [comment]
@vietj you should announce the complete migration to Kotlin 1.3 and coroutines 1.0 on the Kotlin Slack workspace

**Comment by vietj** [comment]
yes, are you present on that space ?

**Comment by gmariotti** [comment]
Yes, should I post something there? I can also share a tweet from you in some of the main channels

**Comment by vietj** [comment]
I've posted there

**Comment by vietj** [comment]
do the most noise you can :-)
