### ISSUE TITLE
Missing package io.vertx.kotlin.ext.web.api.contract

### ISSUE THREAD

**Issue by gmariotti** [vert-x3/vertx-lang-kotlin#96]
It seems that the Kotlin extensions for the `web-api-contract` and `web-api` are no longer generated. Is this expected @vietj?

**Comment by vietj** [comment]
@slinkydeveloper has done a PR for fixing this

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-lang-kotlin/pull/95

**Comment by gmariotti** [comment]
oh great, I wasn't aware of this. Will it be part of a `CR3`?

**Comment by vietj** [comment]
I'm not sure we'll do a CR3, it might be a GA

**Comment by vietj** [comment]
but it will be part of next release :-)
